### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [IvanKor/RTKPOST-and-GPS#1]
Здравствуйте!

Нашёл этот репозиторий по ссылке с форума https://forum.openstreetmap.org/viewtopic.php?pid=852760#p852760

Не желаете добавить разрешение на копирование/изменение/распространение, какую нибудь из популярных opensource лицензий? Информация полезная и уникальная, может кто захочет форкнуть, дополнить или просто где-то использовать.

**Comment by IvanKor** [comment]
Добавил

**Comment by vazhnov** [comment]
MIT license — отлично!
Спасибо!
